### ISSUE TITLE
stringify or toString method?

### ISSUE THREAD

**Issue by devinus** [fb55/css-what#11]
Is there anything that can take `css-what` tokens and return the selector?

**Comment by devinus** [comment]
I'd like to modify that selector, that's why.

**Comment by devinus** [comment]
Ah, I *completely* missed the `stringify.js` file.

**Comment by devinus** [comment]
Actually, I'm still wondering how I can use it. It doesn't look publicly available from the package, is that correct?

**Comment by devinus** [comment]
For more information, I'm currently using css-what to parse and then modify the AST, and I'd like to then stringify the result.

**Comment by fb55** [comment]
`stringify.js` doesn't escape invalid chars yet, that's why it isn't publicly available. Also, the order of parts of the selector isn't fixed (eg. css-select sorts selectors for improved selection speed, their stringified counterpart isn't valid, though), which should probably be fixed, too.

Anyway, the API is fixed and you can use it via

```js
var parse = require("css-what"),
    stringify = require("css-what/stringify");

var sel = parse(…);
… //modify the selector
return stringify(sel);
```

**Comment by devinus** [comment]
I don't believe `stringify` is included in the npm package, unless I'm missing something. Also, `#something` is stringified as `[id=something]`, which doesn't seem optimal.

**Comment by fb55** [comment]
You're right, it's currently not included. ID selectors are properly serialized, though, as are classes. (They are normalized to that form when parsing, as it simplifies the format.)

**Comment by devinus** [comment]
@fb55 If you can tell me how names should be escaped I'd love to take a stab at it. I want `stringify` as a publicly available API and rock solid.

**Comment by fb55** [comment]
There are two cases: Printable ASCII chars that have a special meaning (eg. `#`, `.`, `>` etc. – pretty much every character in a one-char string in the parser), which need a slash in front of them, and every non-printable or non-ASCII code point (including multi-character UTF8 chars), which need to be escaped following eg. [this.](https://mathiasbynens.be/notes/javascript-encoding#surrogate-formulae). I've implemented this for HTML entities in the `entities` module [here](https://github.com/fb55/entities/blob/09ab1a58022de2d573ddad35405d1ddf567c9dda/lib/encode.js#L43-L49), which should be a good starting point.

Escaping printable non-ASCII chars might not be wanted by all users (as it makes selectors written in eg. cyrillic or Chinese/Japanese characters hard to read), this should probably be configurable.
