### ISSUE TITLE
Does not parse anything inside :host() and :host-context()

### ISSUE THREAD

**Issue by zicsus** [fb55/css-what#286]
Hi, 
So I found out that css-what does not parse anything inside :host() and :host-context() and just return the value as it is.

For example: 
If you try to parse `:host-context(#test.cl)` it returns-
`[[{type: "pseudo", name: "host-context", data: "#test.cl"}]]`

Expected output- 
`[[{type: "pseudo", name: "host-context", data: [[ {type:"attribute", name:"id", value="test"....}, {type:"attribute", name:"class", value="cl"....} ]] }]]`

Thanks!

**Comment by fb55** [comment]
`:host` and `:host-context` aren't a part of the current list of pseudo selectors to parse, in https://github.com/fb55/css-what/blob/bf7068e460d178259f8217e65e3948e56776be75/src/parse.ts#L99

Happy to accept a PR that adds them to this list.

**Comment by zicsus** [comment]
> `:host` and `:host-context` aren't a part of the current list of pseudo selectors to parse, in
> 
> https://github.com/fb55/css-what/blob/bf7068e460d178259f8217e65e3948e56776be75/src/parse.ts#L99
> 
> Happy to accept a PR that adds them to this list.

Here you go - https://github.com/fb55/css-what/pull/288

**Comment by fb55** [comment]
Awesome, thanks!
