### ISSUE TITLE
SyntaxError: parenthesis not matched

### ISSUE THREAD

**Issue by 5saviahv** [fb55/css-what#360]
Selector gave me error: SyntaxError: parenthesis not matched

`script:contains("setImgSrc(")`

I tried parsing it for testing

```javascript
const CSSwhat = require('css-what');
CSSwhat.parse('script:contains("setImgSrc(")');

```
but got error: `Uncaught TypeError: CSSwhat.parse is not a function`
  `at parseSelector (/home/.../node_modules/css-what/index.js:226:14)`
... so testing has to wait

but why I got this parenthesis error, **"(" is as text inside data field**, not sure ... maybe you can provide some examples how pseudos data field should be used.

**Comment by fb55** [comment]
The algorithm for parsing `:contains` is not particularly advanced (happy to take PRs with improvements). For now, you can escape the parenthesis for the same effect:

```js
> require('css-what').parse(':contains("asdf\\(")')[0][0]
{ type: 'pseudo', name: 'contains', data: 'asdf(' }
```

**Comment by 5saviahv** [comment]
thanks for tip, it worked
