### ISSUE TITLE
parse xml namespaces

### ISSUE THREAD

**Issue by milahu** [fb55/css-what#512]
css-what breaks on xml documents with namespaces

use case: parse and query `docx` documents with `<w:t>hello</w:t>` etc.

actual

```js
require('css-what').parse('w:t', { xmlMode: true }) ==
[
  [
    { type: 'tag', name: 'w', namespace: null },
    { type: 'pseudo', name: 't', data: null }
  ]
]
```

`css-select` throws `Error: unmatched pseudo-class :t`

expected

```js
require('css-what').parse('w:t', { xmlMode: true }) ==
[
  [
    { type: 'tag', name: 't', namespace: 'w' }
  ]
]
```

possible solution:
parse only valid pseudo elements (`:first-child` etc), and treat the rest as namespaced tags
and/or add an option to disable all pseudo elements, and treat them all as namespaced tags

**Comment by fb55** [comment]
The way to solve this in CSS is by escaping the colon: `w\:t` works without an issue. (Note that you'll have to double-escape the backslash in JS strings, so this would be `"w\\:t"`.)
