### ISSUE TITLE
after upgrade getting "parse is not a function error

### ISSUE THREAD

**Issue by vkpraveen** [fb55/css-what#520]
After upgrade to version "5.0.1" getting an error parse is not a function

Application is created using Create React app template

Error:

node_modules\css-select\lib\compile.js:31
        var token = parse(selector, options);
                    ^

TypeError: parse is not a function

Version:  "5.0.1"

**Comment by fb55** [comment]
Seems like this was solved in https://github.com/fb55/css-select/issues/469!
