### ISSUE TITLE
Update to latest 'laravel-mix'

### ISSUE THREAD

**Issue by jadamec** [fb55/css-what#525]
When upgrading the 'laravel-mix' package to the latest 6.0.24. version, your package has some problem (see below). Would you be so kind to fix it, please? I don't have 5th version of the 'laravel-mix' anymore...

![Screenshot_1](https://user-images.githubusercontent.com/19595874/122735882-b8521a00-d27f-11eb-8ed5-1e5720cb8cd7.jpg)

**Comment by fb55** [comment]
Hi @jadamec, you are (understandably) reading this in the wrong direction. This package was already fixed, but your dependency laravel-mix hasn't been updated yet.

**Comment by jadamec** [comment]
> Hi @jadamec, you are (understandably) reading this in the wrong direction. This package was already fixed, but your dependency laravel-mix hasn't been updated yet.

Oh I see. Sorry for that.
