### ISSUE TITLE
Fails to parse ::part()

### ISSUE THREAD

**Issue by Qix-** [fb55/css-what#761]
It appears `::part()` selectors do not parse and instead emit an error:

```javascript
console.log(cssWhat.parse('foo::part(bar)'));
```
```
Error: Unmatched selector: )
```

**Comment by fb55** [comment]
__Tl;dr__ pseudo-elements aren't allowed to have a value between parentheses.

Pseudo-elements are currently implemented [in line with the CSS Selectors Spec](https://www.w3.org/TR/selectors-3/#pseudo-elements):

> A pseudo-element is made of two colons (::) followed by the name of the pseudo-element.

This is in contrast to pseudo-classes:

> A pseudo-class always consists of a "colon" (:) followed by the name of the pseudo-class and optionally by a value between parentheses.

Hope this makes sense!

**Comment by fb55** [comment]
Just learned about [::part](https://developer.mozilla.org/en-US/docs/Web/CSS/::part). Very odd that this shouldn't be possible based on the spec. If there is a spec extension that allows for this, I am happy to implement it.

**Comment by fb55** [comment]
Okay, so the [grammar](https://drafts.csswg.org/selectors-4/#grammar) for pseudo-elements makes them equivalent to pseudo-classes with a colon in front of them. I will update the parser to support this.

**Comment by fb55** [comment]
I have also opened https://github.com/w3c/csswg-drafts/issues/7186.

**Comment by Qix-** [comment]
Thanks for the quick turnaround! :D Subscribed to the other issue, interested to see what comes of it.
