### ISSUE TITLE
what's the element action?

### ISSUE THREAD

**Issue by MatthewMueller** [fb55/css-what#9]
I would think:

```js
require('css-what')('.hi')
```

would end up looking like:

```
{
  type: 'attribute', 
  action: 'equals',
  name: 'class',
  value: 'hi'
}
```

or `[class="hi"]`.

**Comment by fb55** [comment]
Classes match for a word inside the selector. Your example would be equal to `[class~="hi"]`.

As a simple example:

```html
<tag class="foo bar baz" />
```

is expected to have three classes and therefore match any subset of `.foo.bar.baz`.

The corresponding action would be `element`.

**Comment by MatthewMueller** [comment]
oh good call!
