### ISSUE TITLE
Parsing animations

### ISSUE THREAD

**Issue by devlato** [fb55/css-what#968]
Hi!

Looks like this library can't parse the CSS animation declarations 😅

**Comment by fb55** [comment]
That's true! This library is only focussed on CSS selectors. Media queries and `@keyframe`s have a unique prefix that should make it easy to spot them. Hope that makes sense!

**Comment by devlato** [comment]
@fb55 it makes sense, but makes the library a bit difficult to use for parsing the CSS files containing keyframes 😅
